# make sure this is executable and run to do sanity checks as configured below
# include -c switch on first to erase existing logs
app/console ko:front-end-tests -e prod -s accenture -a dash,ppc,seo,syn,admin -c
app/console ko:front-end-tests -e prod -s fourseasons -a seo,ppc,syn,aud,admin
app/console ko:front-end-tests -e prod -s sandisk -a seo,aud,admin
app/console ko:front-end-tests -e prod -s wallace -a seo,dash,ppc,syn,aud,admin
app/console ko:front-end-tests -e prod -s fairmont -a seo,aud,admin
app/console ko:front-end-tests -e prod -s masterbrand -a seo,dash,aud,admin
app/console ko:front-end-tests -e prod -s denihan -a seo,dash,ppc,syn,aud,admin
app/console ko:front-end-tests -e prod -s swissotel -a seo,aud,admin
app/console ko:front-end-tests -e prod -s raffles -a seo,aud,admin
app/console ko:front-end-tests -e prod -s bmw -a ppc,aud,admin
app/console ko:front-end-tests -e prod -s ariba -a seo,dash,ppc,syn,admin
app/console ko:front-end-tests -e prod -s whartoned -a seo,dash,ppc,syn,aud,admin
app/console ko:front-end-tests -e prod -s ctc -a seo,dash,ppc,syn,aud,admin
app/console ko:front-end-tests -e prod -s nasdaq -a seo,admin
app/console ko:front-end-tests -e prod -s aia -a seo,dash,admin
app/console ko:front-end-tests -e prod -s viceroy -a seo,dash,aud,admin
app/console ko:front-end-tests -e prod -s saparchive -a seo,ppc,admin
app/console ko:front-end-tests -e prod -s scotts -a seo,dash,ppc,syn,admin
app/console ko:front-end-tests -e prod -s tomcat -a seo,dash,ppc,syn,admin
app/console ko:front-end-tests -e prod -s nasdaqnew -a seo,dash,admin
app/console ko:front-end-tests -e prod -s miraclegro -a seo,dash,ppc,syn,admin
app/console ko:front-end-tests -e prod -s roundup -a seo,dash,ppc,syn,admin
app/console ko:front-end-tests -e prod -s ortho -a seo,dash,ppc,syn,admin
app/console ko:front-end-tests -e prod -s mckinsey -a seo,dash,admin
app/console ko:front-end-tests -e prod -s fs-vacationrentals -a seo,dash,admin
app/console ko:front-end-tests -e prod -s cibc2015 -a seo,dash,ppc,syn,admin
app/console ko:front-end-tests -e prod -s godiva -a seo,dash,ppc,syn,admin
app/console ko:front-end-tests -e prod -s accenturecareers -a ppc,admin
app/console ko:front-end-tests -e prod -s naturescare -a seo,dash,ppc,syn,admin
app/console ko:front-end-tests -e prod -s parkway -a dash,ppc,admin
app/console ko:front-end-tests -e prod -s guardian -a seo,dash,admin
app/console ko:front-end-tests -e prod -s set -a ppc,da,admin
app/console ko:front-end-tests -e prod -s nexgard -a ppc,da,admin
app/console ko:front-end-tests -e prod -s frontline -a ppc,da,admin
app/console ko:front-end-tests -e prod -s scottsco -a ppc,admin
app/console ko:front-end-tests -e prod -s nypresbyterian -a seo,admin
app/console ko:front-end-tests -e prod -s optimum-sealy -a ppc,da,admin
app/console ko:front-end-tests -e prod -s posturepedic -a ppc,da,admin
app/console ko:front-end-tests -e prod -s tempurpedic -a ppc,da,admin
app/console ko:front-end-tests -e prod -s stearnsfoster -a ppc,da,admin
app/console ko:front-end-tests -e prod -s sealy -a ppc,da,admin
app/console ko:front-end-tests -e prod -s frontier -a seo,dash,admin
app/console ko:front-end-tests -e prod -s langham -a seo,dash,ppc,syn,admin
app/console ko:front-end-tests -e prod -s sapm -a seo,dash,ppc,syn,aud,da,admin
app/console ko:front-end-tests -e prod -s sap-community -a seo,aud,admin
app/console ko:front-end-tests -e prod -s sap-store -a seo,admin
app/console ko:front-end-tests -e prod -s successfactors -a seo,dash,aud,admin
app/console ko:front-end-tests -e prod -s hybris -a seo,aud,admin
app/console ko:front-end-tests -e prod -s sap-dlm -a seo,admin
app/console ko:front-end-tests -e prod -s crystalreports -a seo,admin
app/console ko:front-end-tests -e prod -s sap-foc -a seo,admin
app/console ko:front-end-tests -e prod -s globenewswire -a seo,admin
app/console ko:front-end-tests -e prod -s ironmountain -a seo,dash,admin
