#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';
require __DIR__.'/config.php';

use Symfony\Component\Console\Application;
use Command\RunTestsCommand;

$application = new Application();

// ... register commands
$application->add(new RunTestsCommand($params));

$application->run();

